// Package wizard implements the CLI subcommands.
//
// Files in this package are intentionally thin: they shell out to
// `docker compose` and edit small config files. Heavy logic belongs in
// sibling internal packages so it can be tested without docker.
package wizard

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/localmind/localmind/wizard/internal/hwdetect"
	"github.com/localmind/localmind/wizard/internal/profile"
)

// Init detects hardware, prints the picked profile, and writes .env.
func Init(ctx context.Context, _ []string) error {
	host := hwdetect.Detect()
	profile := hwdetect.Pick(host)

	fmt.Printf("detected: os=%s arch=%s ram=%dGB gpu=%q vram=%dGB\n",
		host.OS, host.Arch, host.RAMGB, host.GPUVendor, host.GPUVRAMGB)
	fmt.Printf("picked profile: %s\n", profile)

	root, err := repoRoot()
	if err != nil {
		return err
	}

	envPath := filepath.Join(root, ".env")
	contents := fmt.Sprintf(`# generated by `+"`localmind init`"+`
LOCALMIND_PROFILE=%s
WEBUI_PORT=3000
OLLAMA_PORT=11434
WHISPER_PORT=9000
PIPER_PORT=10200
MCP_PORT=7800
WEBUI_AUTH=true
`, profile)

	if err := os.WriteFile(envPath, []byte(contents), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", envPath, err)
	}
	fmt.Printf("wrote %s\n", envPath)
	fmt.Println("next: `localmind up`")
	return nil
}

// Up brings the stack up with overlays appropriate to the host. After a
// successful compose up, kicks off the hardware profiler unless --no-profile
// is passed or a previous result already exists. Profiler failures are logged
// but never fail the Up command.
func Up(ctx context.Context, args []string) error {
	composeArgs, skipProfile := splitProfileFlag(args)
	if err := composeRun(ctx, append([]string{"up", "-d"}, composeArgs...)); err != nil {
		return err
	}

	root, err := repoRoot()
	if err != nil {
		return err
	}
	if skipProfile {
		return nil
	}
	if profile.ShouldSkip(root, false) {
		fmt.Printf("==> profiler: skipping (existing %s; run `localmind profile --force` to re-run)\n",
			profile.ProfilePath(root))
		return nil
	}
	if _, err := profile.Run(ctx, profile.Config{
		RepoRoot:      root,
		OllamaBaseURL: ollamaURLFromEnv(root),
	}); err != nil {
		log.Printf("profiler: %v (continuing)", err)
	}
	return nil
}

// Profile runs the hardware profiler manually. Pass --force to re-run even
// when a previous result exists.
func Profile(ctx context.Context, args []string) error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	force := false
	for _, a := range args {
		if a == "--force" || a == "-f" {
			force = true
		}
	}
	if profile.ShouldSkip(root, force) {
		fmt.Printf("profiler already ran. pass --force to re-run.\nresult: %s\n",
			profile.ProfilePath(root))
		return nil
	}
	_, err = profile.Run(ctx, profile.Config{
		RepoRoot:      root,
		OllamaBaseURL: ollamaURLFromEnv(root),
	})
	return err
}

// splitProfileFlag pulls --no-profile out of the args list. The remaining
// args are forwarded verbatim to docker compose.
func splitProfileFlag(args []string) ([]string, bool) {
	out := make([]string, 0, len(args))
	skip := false
	for _, a := range args {
		if a == "--no-profile" {
			skip = true
			continue
		}
		out = append(out, a)
	}
	return out, skip
}

// ollamaURLFromEnv reads OLLAMA_BASE_URL or OLLAMA_PORT from <root>/.env so
// the profiler hits whatever port the user configured. Falls back to the
// compose default.
func ollamaURLFromEnv(root string) string {
	envPath := filepath.Join(root, ".env")
	body, err := os.ReadFile(envPath)
	if err != nil {
		return "http://localhost:11434"
	}
	port := "11434"
	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if k, v, ok := strings.Cut(line, "="); ok {
			switch strings.TrimSpace(k) {
			case "OLLAMA_BASE_URL":
				return strings.Trim(strings.TrimSpace(v), `"'`)
			case "OLLAMA_PORT":
				port = strings.Trim(strings.TrimSpace(v), `"'`)
			}
		}
	}
	return "http://localhost:" + port
}

// Down stops the stack.
func Down(ctx context.Context, args []string) error {
	return composeRun(ctx, append([]string{"down"}, args...))
}

// Status shows container health.
func Status(ctx context.Context, _ []string) error {
	return composeRun(ctx, []string{"ps"})
}

// Backup snapshots the docker volumes to an archive. Stub: real impl will
// run a tiny alpine helper container that tars/zstds the volumes.
func Backup(ctx context.Context, _ []string) error {
	return fmt.Errorf("backup: not yet implemented")
}

// Doctor diagnoses common problems.
func Doctor(ctx context.Context, _ []string) error {
	checks := []struct {
		name string
		fn   func() error
	}{
		{"docker on PATH", func() error { _, err := exec.LookPath("docker"); return err }},
		{"docker compose plugin", checkDockerCompose},
		{"repo root resolvable", func() error { _, err := repoRoot(); return err }},
	}
	allOK := true
	for _, c := range checks {
		if err := c.fn(); err != nil {
			fmt.Printf("FAIL  %s: %v\n", c.name, err)
			allOK = false
			continue
		}
		fmt.Printf("OK    %s\n", c.name)
	}
	if !allOK {
		return fmt.Errorf("one or more checks failed")
	}
	return nil
}

// composeRun shells out to `docker compose` with the right -f overlays
// based on the detected host.
func composeRun(ctx context.Context, sub []string) error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	files := []string{"-f", "docker-compose.yml"}
	switch hostKind() {
	case "nvidia":
		files = append(files, "-f", filepath.Join("compose", "compose.gpu.nvidia.yml"))
	case "apple":
		files = append(files, "-f", filepath.Join("compose", "compose.gpu.apple.yml"))
	}

	full := append([]string{"compose"}, files...)
	full = append(full, sub...)

	cmd := exec.CommandContext(ctx, "docker", full...)
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func hostKind() string {
	h := hwdetect.Detect()
	if h.GPUVendor == "nvidia" {
		return "nvidia"
	}
	if runtime.GOOS == "darwin" && runtime.GOARCH == "arm64" {
		return "apple"
	}
	return "cpu"
}

// repoRoot finds the directory holding docker-compose.yml. We walk up
// from the cwd; this lets `localmind` work from any subdirectory.
func repoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	d := cwd
	for {
		if _, err := os.Stat(filepath.Join(d, "docker-compose.yml")); err == nil {
			return d, nil
		}
		parent := filepath.Dir(d)
		if parent == d {
			return "", fmt.Errorf("docker-compose.yml not found in %s or any parent", cwd)
		}
		d = parent
	}
}

func checkDockerCompose() error {
	out, err := exec.Command("docker", "compose", "version").CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
